{% set name = "steem" %}
{% set version = "1.0.0" %}
{% set sha256 = "c9ba0db870c0ae8d89f324584ca931ca9a35a5d69112101d6cfad35c199b42c3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - piston = steem.cli:legacy
    - steempy = steem.cli:legacy
    - steemtail = steem.cli:legacy

requirements:
  build:
    - python
    - pip
    - sphinx
    - autopep8
    - yapf
    - sphinxcontrib-restbuilder
    - sphinxcontrib-programoutput
    - recommonmark
    - pypandoc
    - pytest-pylint
    - pep8

  run:
    - python
    - setuptools
    - scrypt >=0.8.0
    - appdirs
    - certifi
    - ecdsa >=0.13
    - pycrypto >=1.9.1
    - pylibscrypt >=1.6.1
    - toolz
    - urllib3
    - w3lib
    - langdetect
    - prettytable
    - voluptuous
    - chardet
    - pytz
    - pytzdata
    - ujson
    - funcy
    - dateparser
    - requests
    - diff-match-patch
    - future
    - futures

test:
  imports:
    - steem
    - steem.account
    - steem.amount
    - steem.post
    - steem.dex
    - steem.aes
    - steem.block
    - steem.blockchain
    - steem.cli
    - steem.commit
    - steem.converter
    - steem.instance
    - steem.profile
    - steem.steem
    - steem.steemd
    - steem.transactionbuilder
    - steem.utils
    - steem.wallet
    - steem.witness
    - steembase
    - steembase.account
    - steembase.base58
    - steembase.bip38
    - steembase.chains
    - steembase.exceptions
    - steembase.http_client
    - steembase.operationids
    - steembase.operations
    - steembase.storage
    - steembase.transactions
    - steembase.types

  commands:
    - conda inspect linkages -p $PREFIX steem  # [not win]
    - conda inspect objects -p $PREFIX steem   # [osx]
    - steemtail --help
    - steempy --help
    - piston --help

about:
  home: https://github.com/steemit/steem-python
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/steemit/steem-python
  doc_url: https://github.com/steemit/steem-python
  summary: 'Official python steem library'

extra:
  recipe-maintainers:
    - holgern
