travis:
  secure:
    BINSTAR_TOKEN: kx4b9gaWdt+nxPuGUvcYOY1NbhEeEZu55BjOt2we2Hgde+mW22K9z6pNSJQjyIZWCMIfAOcUwdwVfAn5CStTbAI7OfaHjkGG3NXqJmPQX1OuckDn5DYtgXCErzOTfj/prIrQ3kaqVHVdkq3B7Dq5G65d+C8SbWgEtclUC/rfvq0FJf9uuxUnz7LnmGZecTY8apJw7kqB82rqb2LzjnIXTzF6i/IiXmNedKNuo/4oC+CQCv9xpBEAp8uYmw3tDBjtOsfDPL+hON3MnHRjtHjuSF/DYoZgE7ynk7yF9k0peZL7Ikr4cOhlcJ5enI5RDDB3sRYmPgcj4Wal0gzgisGOyKm4ZsY/KvOkuW1QqC5RVnszz9yLnf+Lznn5sAPsHHlGym1Bonmjco1MpRbxhX5U80iioJtFwxJxtEPyfgFNZztn6cONAwGpmWZZgYWIqKbvNZRKlVE5F+aEJM3lT5OM0nmOg8K/YjuczRIAs/4vvjIYXDwObhPbhjyAfHpDXxRjnYLqT+VOj7/b1iqz2DMR6xNU0DxACRBGMR0rGfD4UyS1SjxOK8nGbkc2iMwWcUHaSw3eOPrk4ZN3XBdxiUe2B0eueL50L/3ae4mrNRwgXrTzLJEY+icXPZTCe4E0bi9vZkrbNstfR2fjSE9GG2L4O60JTwZKm0fuEuLsTw3y2mE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
